export const FETCHING_ASSETS_BALANCE = 'FETCHING_ASSETS_BALANCE';
export const FETCH_ASSETS_BALANCE_SUCCEED = 'FETCH_ASSETS_BALANCE_SUCCEED';
export const FETCH_ASSETS_BALANCE_FAILED = 'FETCH_ASSETS_BALANCE_FAILED';
