export const LOGGING_IN = 'LOGGING_IN';
export const LOG_IN_SUCCEED = 'LOG_IN_SUCCEED';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';

export const FETCHING_WALLET_INFO = 'FETCHING_WALLET_INFO';
export const FETCH_WALLET_SUCCEED = 'FETCH_WALLET_SUCCEED';
export const FETCH_WALLET_FAILED = 'FETCH_WALLET_FAILED';
